Script started on Fri 05 Dec 2014 12:41:08 AM PST
~
amacp001@hammer $ cs100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.                               |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32mamacp001[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cs10[K[K[Kd cs100/hw/rshell
[s%%%%%%%%%%[u[0;32mamacp001[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/hw/rshell[0;95m (master) [0;36m$[0m ls
LICENSE  Makefile  README.md  src  tests
[s%%%%%%%%%%[u[0;32mamacp001[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/hw/rshell[0;95m (master) [0;36m$[0m bin [K[K[K[Kmake rshell
mkdir -p "bin"
cd bin; g++ ../src/rshell.cpp -g -Wall -Werror -pedantic -ansi -o rshell
[s%%%%%%%%%%[u[0;32mamacp001[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/hw/rshell[0;95m (master) [0;36m$[0m bin/rshell
~/cs100/hw/rshell $ pwf d ; echo test    this is a test ; ct at LICENSE
/class/classes/amacp001/cs100/hw/rshell
this is a test
Copyright (c) 2014, Mike Izbicki
All rights reserved.

All bash scripts licensed under the BSD3.

All other content licensed under the Creative Commons Attribute Share-alike 4.0.
~/cs100/hw/rshell $ cd
~ $ pwd
/class/classes/amacp001
~ $ cd    ls
cs10   cs12  cs61     Documents  ee120B  Pictures  sketchbook  Videos
cs100  cs14  Desktop  Downloads  Music	 Public    Templates
~ $ cd cs10
~/cs10 $ ls
assignments  labs
~/cs10 $ cd assa	 i	gnments
~/cs10/assignments $ ls
assignment_1   assignment_2  assignment_4  assignment_6  assignment_8
assignment_10  assignment_3  assignment_5  assignment_7  assignment_9
~/cs10/assignments $ cd assignment_1 assignment_2
~ $ ls
cs10   cs12  cs61     Documents  ee120B  Pictures  sketchbook  Videos
cs100  cs14  Desktop  Downloads  Music	 Public    Templates
~ $ cd cs100/hw/rshell && s ls
bin  LICENSE  Makefile	README.md  src	tests
~/cs100/hw/rshell $ cd notThere
chdir: No such file or directory
~/cs100/hw/rshell $ ^C
^C
^C
echo

~/cs100/hw/rshell $ echo ^C
test
~/cs100/hw/rshell $ cat ^C
repeat what I say
execv: No such file or directory
~/cs100/hw/rshell $ cat
reper at what I say
repeat what I say
rs  src/    LICENSE
LICENSE
^C
~/cs100/hw/rshell $ make cp
mkdir -p "bin"
cd bin; g++ ../src/cp.cpp -g -Wall -Werror -pedantic -ansi -o cp
~/cs100/hw/rshell $ bin/cp.  /usr/share/dict/linux.words tmp.tsts   xtx 
~/cs100/hw/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests  tmp.txt
~/cs100/hw/rshell $ rm tmp.txt
~/cs100/hw/rshell $ bin/cp /usr/share/dict/linux.words -a tmp.txt
Times for in.get(char) and out.put(char)
wallclock time: 0.443448
user time: 0.310953
system time: 0.008999

remove: No such file or directory
Times for read() and write() one character at a time
wallclock time: 7.18836
user time: 0.425935
system time: 6.69098

Times for read() and write() one buffer at a time
wallclock time: 7.3829
user time: 0.454931
system time: 6.79597
~/cs100/hw/rshell $ ls
bin  LICENSE  Makefile	README.md  src	tests
~/cs100/hw/rshell $ r bin/rshell
~/cs100/hw/rshell $ ^C

^C

exit
~/cs100/hw/rshell $ exit
[s%%%%%%%%%%[u[0;32mamacp001[0;36m@[0;32mcs100[0;36m:[0;32m~/cs100/hw/rshell[0;95m (master) [0;36m$[0m exit
exit
~
amacp001@hammer $ exit
exit

Script done on Fri 05 Dec 2014 12:49:50 AM PST
